TodoList/Models/ErrorViewModel.cs
namespace TodoList.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

TodoList/Models/TodoListWithItemsViewModel.cs
using TodoList.Business.Project.ViewModels;

namespace TodoList.Models;

public record TodoListWithItemsViewModel(
    ProjectViewModel Project
    // UserStoryViewModel[] TodoItems,
    // UserStoryViewModel? UpdatingTodoItem = null
);

TodoList/Controllers/AbstractController.cs
using Microsoft.AspNetCore.Mvc;

namespace TodoList.Controllers;

public abstract class AbstractController : Controller
{
    protected const string UserIdCookieKey = "UserId";

    protected int? GetUserIdFromCookie()
    {
        Request.Cookies.TryGetValue(UserIdCookieKey, out var userId);
        return string.IsNullOrWhiteSpace(userId) ? null : int.Parse(userId);
    }

    protected bool HasUserAuthenticated() => GetUserIdFromCookie() is not null;

    protected void SetUserIdCookie(int id)
    {
        var cookieBuilder = new CookieBuilder();
        cookieBuilder.Name = UserIdCookieKey;
        cookieBuilder.Expiration = DateTime.Now.AddDays(1).TimeOfDay;

        HttpContext.Response.Cookies.Append(key: cookieBuilder.Name, id.ToString());
        cookieBuilder.Build(HttpContext);
    }

    protected void DeleteUserIdCookie()
    {
        HttpContext.Response.Cookies.Delete(UserIdCookieKey);
    }

    protected IActionResult RedirectToLoginView() => RedirectToAction(actionName: "Index", controllerName: "Login");
}

TodoList/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using TodoList.Business.Authentication;

namespace TodoList.Controllers;

public class LoginController : AbstractController
{
    private readonly AuthBusiness _authBusiness;

    public LoginController(AuthBusiness authBusiness)
    {
        _authBusiness = authBusiness;
    }

    [HttpGet]
    public IActionResult Index()
    {
        if (HasUserAuthenticated())
            return RedirectToTodoListIndex();

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(string username, string password)
    {
        await _authBusiness.LoginAsync(username, password);

        var user = (await _authBusiness.GetUserAsync(username))!;

        SetUserIdCookie(user.Id);

        return RedirectToTodoListIndex();
    }


    private IActionResult RedirectToTodoListIndex()
        => RedirectToAction(actionName: "Index", controllerName: "TodoList");
}

TodoList/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Mvc;

namespace TodoList.Controllers;

public class LogoutController : AbstractController
{
    [HttpPost]
    public IActionResult Logout()
    {
        DeleteUserIdCookie();
        return RedirectToAction(actionName: "Index", controllerName: "Login");
    }
}

TodoList/Controllers/RegisterController.cs
using System.Net.Mail;
using Microsoft.AspNetCore.Mvc;
using TodoList.Business.Authentication;
using TodoList.Controllers.Exceptions;
using TodoList.Infrastructure.Util;

namespace TodoList.Controllers;

public class RegisterController : AbstractController
{
    private readonly AuthBusiness _authBusiness;

    public RegisterController(AuthBusiness authBusiness)
    {
        _authBusiness = authBusiness;
    }

    [HttpGet]
    public IActionResult Index()
    {
        if (HasUserAuthenticated())
            return RedirectToTodoListIndex();

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Register(string username, string password, string email)
    {
        Guard.Assert<InvalidEmailAddressException>(MailAddress.TryCreate(email, out _));
        
        await _authBusiness.RegisterAsync(new AuthBusiness.RegisterDto(username, password, email));
        return RedirectToTodoListIndex();
    }

    private IActionResult RedirectToTodoListIndex()
        => RedirectToAction(actionName: "Index", controllerName: "TodoList");
}

TodoList/Controllers/TodoItemController.cs
using Microsoft.AspNetCore.Mvc;
using TodoList.Business.Common.Exceptions;
using TodoList.Business.Project;
using TodoList.Infrastructure.Util;
using TodoList.Models;

namespace TodoList.Controllers;

public class TodoItemController : AbstractController
{
    private readonly ProjectBusiness _projectBusiness;

    public TodoItemController(ProjectBusiness projectBusiness)
    {
        _projectBusiness = projectBusiness;
    }

    [HttpGet]
    public async Task<IActionResult> Index(int todoListId)
    {
        if (HasUserAuthenticated() is false)
            return RedirectToLoginView();

        throw new NotImplementedException();
        //
        // var todoList = await _projectBusiness.GetByIdAsync(todoListId);
        // var todoItems = await _projectBusiness.GetUserStoriesAsync(todoListId);
        //
        // return View(new TodoListWithItemsViewModel(todoList, todoItems));
    }

    [HttpGet]
    public async Task<IActionResult> GetTodoItem(int todoListId, int todoItemId)
    {
        if (HasUserAuthenticated() is false)
            return RedirectToLoginView();

        throw new NotImplementedException();
        //
        // var todoList = await _projectBusiness.GetByIdAsync(todoListId);
        // var todoItems = await _projectBusiness.GetUserStoriesAsync(todoListId);
        // var todoItem = await _projectBusiness.GetTodoItemAsync(todoItemId);
        //
        // return View("Index", new TodoListWithItemsViewModel(todoList, todoItems, UpdatingTodoItem: todoItem));
    }

    [HttpPost]
    public async Task<IActionResult> Create(int todoListId, TodoItemDto dto)
    {
        throw new NotImplementedException();

        // Guard.Assert<TitleIsRequiredException>(string.IsNullOrWhiteSpace(dto.Title) is false);
        //
        // await _projectBusiness.AddTodoItemAsync(todoListId, new[] { dto });
        // return RedirectToIndex(todoListId);
    }

    [HttpPost]
    public async Task<IActionResult> MakeItDone(int todoListId, int todoItemId)
    {
        // await _projectBusiness.MakeTodoItemDone(todoListId, todoItemId);

        return RedirectToIndex(todoListId);
    }

    [HttpPost]
    public async Task<IActionResult> MakeItUndone(int todoListId, int todoItemId)
    {
        // await _projectBusiness.MakeTodoItemUndone(todoListId, todoItemId);

        return RedirectToIndex(todoListId);
    }

    [HttpPost]
    public async Task<IActionResult> Update(int todoListId, int todoItemId, TodoItemDto dto)
    {
        Guard.Assert<TitleIsRequiredException>(string.IsNullOrWhiteSpace(dto.Title) is false);

        throw new NotImplementedException();

        // await _projectBusiness.UpdateTodoItemAsync(todoListId, todoItemId, dto);
        // return RedirectToIndex(todoListId);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(int todoListId, int todoItemId)
    {
        throw new NotImplementedException();
        //
        // await _projectBusiness.DeleteTodoItemsAsync(todoListId, todoItemId);
        // return RedirectToIndex(todoListId);
    }

    private IActionResult RedirectToIndex(int todoListId) => RedirectToAction("Index", new { todoListId = todoListId });
}

TodoList/Controllers/TodoListController.cs
using Microsoft.AspNetCore.Mvc;
using TodoList.Business.Common.Exceptions;
using TodoList.Business.Project;
using TodoList.Controllers.Exceptions;
using TodoList.Infrastructure.Util;

namespace TodoList.Controllers;

public class TodoListController : AbstractController
{
    private readonly ProjectBusiness _projectBusiness;

    public TodoListController(ProjectBusiness projectBusiness)
    {
        _projectBusiness = projectBusiness;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        if (HasUserAuthenticated() is false)
            return RedirectToLoginView();

        var userId = GetUserIdFromCookie()!.Value;

        var viewModels = await _projectBusiness.GetAsync(userId);

        return View(viewModels);
    }

    [HttpPost]
    public async Task<IActionResult> Create(string title)
    {
        Guard.Assert<TitleIsRequiredException>(string.IsNullOrWhiteSpace(title) is false);
        Guard.Assert<ContentInvalidLengthException>(title.Length <= 128);

        var userId = GetUserIdFromCookie()!;
        await _projectBusiness.CreateAsync(title, userId.Value);

        return RedirectToIndex();
    }

    [HttpPost]
    public async Task<IActionResult> Delete(int id)
    {
        await _projectBusiness.DeleteAsync(id);
        return RedirectToIndex();
    }


    private IActionResult RedirectToIndex() => RedirectToAction(nameof(Index));
}

TodoList/Views/Login/Index.cshtml
@{
    Layout = "_Layout";
}

<div class="container mt-5 loginCard">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <svg class="bi bi-person-fill solid-white icon-center mb-3" xmlns="http://www.w3.org/2000/svg" fill="currentColor" width="160" height="160" viewBox="0 0 16 16">
                        <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"></path>
                    </svg>

                    <form method="post" action="/Login/Login">
                        <div class="mb-3">
                            <input class="form-outline rounded w-100" type="text" name="username" id="username" placeholder="Username" required>
                            <span class="error-message" id="usernameErrorMessage">Username is required</span>
                        </div>
                        <div class="mb-3">
                            <input class="form-outline rounded w-100" type="password" name="password" id="password" placeholder="Password" required>
                            <span class="error-message" id="passwordErrorMessage">Password is required</span>
                        </div>
                        <button class="btn btn-primary w-100 mb-2" type="submit" onclick="validateInputs()">Login</button>
                    </form>
                    <form method="get" action="/Register/Index">
                        <button class="btn btn-info w-100" type="submit">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function validateInputs() {
        const usernameInput = document.getElementById("username");
        const passwordInput = document.getElementById("password");
        const usernameError = document.getElementById("usernameErrorMessage");
        const passwordError = document.getElementById("passwordErrorMessage");
    
        if (usernameInput.value.trim() === "") {
            usernameError.style.display = "block";
        } else {
            usernameError.style.display = "none";
        }
    
        if (passwordInput.value.trim() === "") {
            passwordError.style.display = "block";
        } else {
            passwordError.style.display = "none";
        }
    }
</script>

TodoList/Views/Register/Index.cshtml
@{
    Layout = "_Layout";
}

<div class="container mt-5 registerCard">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <svg class="bi bi-person-fill-add solid-white icon-center mb-3" xmlns="http://www.w3.org/2000/svg" width="160" height="160" fill="currentColor" viewBox="0 0 16 16">
                        <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0m-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                        <path d="M2 13c0 1 1 1 1 1h5.256A4.5 4.5 0 0 1 8 12.5a4.5 4.5 0 0 1 1.544-3.393Q8.844 9.002 8 9c-5 0-6 3-6 4"/>
                    </svg>

                    <form method="post" action="/Register/Register" id="registerForm">
                        <div class="mb-3">
                            <input class="form-outline rounded w-100" type="text" name="username" id="username" placeholder="Username"  required/>
                            <span class="error-message" id="usernameErrorMessage">Username is required</span>

                        </div>
                        <div class="mb-3">
                            <input class="form-outline rounded w-100" placeholder="Email" type="email" id="email" name="email" required/>
                            <span class="error-message" id="emailErrorMessage">Email is required</span>
                        </div>
                        <div class="mb-3">
                            <input class="form-outline rounded w-100" placeholder="Password" type="password" id="password" name="password" oninput="confirmPassword()" required/>
                            <span class="error-message" id="passwordErrorMessage">Password is required</span>
                        </div>
                        <div class="mb-3">
                            <input class="form-outline rounded w-100" placeholder="Confirm password" type="password" id="confirmpassword" name="confirmpassword" oninput="confirmPassword()" required/>
                            <span class="error-message" id="confirmpasswordErrorMessage">Confirm password is required</span>
                        </div>
                        <button class="btn btn-info w-100 mb-2" type="submit" onclick="validateInputs()">Register</button>
                    </form>
                    <form method="get" action="/Login/Index">
                        <button class="btn btn-primary w-100 w-100" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function validateInputs() {
        const usernameInput = document.getElementById("username");
        const usernameError = document.getElementById("usernameErrorMessage");
        
        if (usernameInput.value.trim() === "") {
            usernameError.style.display = "block";
        } else {
            usernameError.style.display = "none";
        }
        
        
        const emailInput = document.getElementById("email");
        const emailError = document.getElementById("emailErrorMessage");
        
        if (emailInput.value.trim() === "") {
            emailError.style.display = "block";
        } else {
            emailError.style.display = "none";
        }
        
        
        const passwordInput = document.getElementById("password");
        const passwordError = document.getElementById("passwordErrorMessage");
        
        if (passwordInput.value.trim() === "") {
            passwordError.style.display = "block";
        } else {
            passwordError.style.display = "none";
        }
        
        
        const confirmPasswordInput = document.getElementById("confirmpassword");
        const confirmPasswordError = document.getElementById("confirmpasswordErrorMessage");
        
        if (confirmPasswordInput.value.trim() === "") {
            confirmPasswordError.style.display = "block";
        } else {
            confirmPasswordError.style.display = "none";
        }
    }
    
    function confirmPassword() {
        var password = document.getElementById("password");
        var confirmPassword = document.getElementById("confirmpassword");
    
        if (password.value === confirmPassword.value) {
            password.classList.remove("border-danger");
            confirmPassword.classList.remove("border-danger");
        } else {
            password.classList.add("border-danger");
            confirmPassword.classList.add("border-danger");
        }
    }
    
    function validatePassword(event) {
        console.log(event);
            var password = document.getElementById("password").value;
            var confirmpassword = document.getElementById("confirmpassword").value;
    
            if (password !== confirmpassword) {
                alert("Passwords do not match");
                event.preventDefault();
            }
        }
        
    document.getElementById("registerForm").addEventListener("submit", validatePassword);
</script>

TodoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Task Tracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/TodoList.styles.css" asp-append-version="true"/>
</head>
<body>
@if (Context.Request.Cookies.TryGetValue("UserId", out _))
{
    <form method="post" action="/Logout/Logout">
        <button class="btn btn-outline-danger" style="position: absolute; top: 10px; left: 10px;" type="submit">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0z"></path>
                <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708z"></path>
            </svg>
        </button>
    </form>
}


<header class="appHeader">
    <nav class="navbar nav-dark-theme navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand mx-auto" asp-area="" asp-controller="TodoList" asp-action="Index">Task Tracker</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>
</header>
<div class="container body-container">
    <main role="main" class="pb-3">
        <div style="margin-top: 5rem"></div>

        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
        }

        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted"></footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<style>
    .appHeader {
        position: fixed;
        top: 0;
        margin: 0 auto;
        width: 350px;
        transform: translate(-50%);
        left: 50%;
    
    }

    .navbar.nav-dark-theme {
        background-color: #eee;
        border-radius: 0 0 8px 8px;
        box-shadow: 8px 4px 8px #ccc;
    }

        .navbar.nav-dark-theme A {
            color: #444;
        }
    .taskInput {
        border-radius: 40px;
        background: #eee;
    }
    input,
    textarea {
        background-color:#eee;
        color: #444;
    }
    
    input:focus,
    select:focus,
    textarea:focus,
    button:focus {
        outline: none;
    }
    
    .card {
       background-color: #444;
       border: none;
    }
    
    .btn-primary {
       background-color: #007bff;
       border-color: #007bff;
    }
    .btn-primary:hover {
       background-color: #0056b3;
       border-color: #0056b3;
    }
    .btn-info {
        background-color: #31d2f2;
        border-color: #31d2f2;
    }
    .btn-info:hover {
       background-color: #2793a3;
       border-color: #2793a3;
    }
    
    svg.solid-white {
        filter: invert(100%);
    }
    svg.icon-center {
        display: block;
        margin: auto;
    }
    tr {
        background: #fff;
        color: #444
    }

    tbody tr:hover {
        cursor: pointer;
        background-color: #ddd;
    }

    th {
        background: #444 !important;
        color: #EEE;
    }

    .mt-5.registerCard,
    .mt-5.loginCard  {
        margin-top: 50% !important;
        transform: translateY(-50%);
    }
    
    .alert.alert-danger {
        color:#842029;
        background-color:#f8d7da;
        border-color:#f5c2c7;
        position: fixed;
        bottom: 20px;
        left: 50%;
        transform: translateX(-50%);
    }
    
    .error-message{
        color: red;
         display: none;
    }
</style>

TodoList/Views/TodoList/Index.cshtml
@model TodoList.Business.Project.ViewModels.ProjectViewModel[]

@{
    Layout = "_Layout";
}

<form method="post" action="/TodoList/Create">
    <div class="d-flex justify-content-between">
        <input class="form-outline custom-width taskInput" placeholder="Add a list" type="text" id="title" name="title" />
        <button class="btn btn-primary me-2" type="submit">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16" style="--darkreader-inline-fill: currentColor;" data-darkreader-inline-fill="">
                <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2"></path>
            </svg>
        </button>
    </div>
</form>

<br/>
<br/>

<table class="table">
    <thead>
    <tr>
        <th class="dark-theme">Title</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var todoList in Model)
    {
        <tr data-href="@Url.Action("Index", "TodoItem", new { todoListId = todoList.Id })">
            <td>
                <div class="d-flex justify-content-between">
                    <p>@todoList.Title</p>
                    <form asp-controller="TodoList" asp-action="Delete" method="post" onclick="return confirm('Are you sure you want to delete this record?')">
                        <input type="hidden" name="id" value="@todoList.Id"/>
                        <button class="btn btn-outline-danger" type="submit">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16" style="--darkreader-inline-fill: currentColor;" data-darkreader-inline-fill="">
                                <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"></path>
                            </svg>
                        </button>
                    </form>
                </div>
            </td>
        </tr>
    }
    </tbody>
</table>

<script>
    var rows = document.getElementsByTagName('table')[0].rows;
    
    Array.from(rows).forEach((row, index) => {
        
        if (index == 0) return;
        
        row.addEventListener("click", function() {
            window.location.href = this.getAttribute('data-href');
        });
    });
</script>

<style>
    tr {
        color: white;
    }

    tbody tr:hover {
        cursor: pointer;
        background-color: #323130;
    }
    
    .dark-theme {
        color: white
    }
    
    .custom-width {
            width: 680px
        }
</style>